name: photo_ease
description: Simple Flutter image editor app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  flutter_localizations:
    sdk: flutter

  # Image handling
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  image: ^4.2.0

  # Storage & paths
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  http: ^1.5.0

  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  assets:
    - assets/fonts/Roboto-Regular.ttf
