name: photo_ease
description: Simple Flutter image editor app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:

  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  cupertino_icons: ^1.0.8


  flutter_localizations:
    sdk: flutter

  # Image handling
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  image: ^4.2.0


  # Storage & paths
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  http: ^1.5.0

  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Roboto-Regular.ttf


    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/sample1.jpg
    - assets/images/sample2.jpg
    - assets/images/sample3.jpg
    - assets/images/sample4.jpg
    - assets/images/sample5.jpg
    - assets/images/sample6.jpg
    - assets/images/sample7.jpg
    - assets/images/sample8.jpg
    - assets/images/sample9.jpg
